name: Deploy to Dev
run-name: Deploy to Dev - 100%

on:
  push:
    branches: [ main ]

env:
  BASE_DOMAIN: ${{ vars.BASE_DOMAIN }}
permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write
  statuses: write
  deployments: write

jobs:
  get-sha:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build Image
    uses: ./.github/workflows/app-cloudrun-build.yaml
    with:
      environment: dev

    secrets: inherit

  deploy:
    name: Deploy Dev - 100%
    needs: [get-sha, build]
    uses: ./.github/workflows/app-deploy-to.yaml
    with:
      environment: dev
      image-tag: ${{ needs.build.outputs.image-tag }}
      deployment-tag: dev-${{ needs.get-sha.outputs.sha }}
      deployment-env: dev
      version: ${{ needs.get-sha.outputs.sha }}
      tag-only: false
    secrets: inherit
